// Our movie model
class Movie {
  final int id, year, numOfRatings, criticsReview, metascoreRating;
  final double rating;
  final List<String> genra;
  final String plot, title, poster, backdrop, watchType, watchTime;
  final List<Map> cast;

  Movie(
      {this.poster,
      this.backdrop,
      this.title,
      this.id,
      this.year,
      this.numOfRatings,
      this.criticsReview,
      this.metascoreRating,
      this.rating,
      this.genra,
      this.plot,
      this.cast,
      this.watchType,
      this.watchTime});
}

// our demo data movie data
List<Movie> movies = [
  Movie(
    id: 1,
    title: "Bloodshot",
    year: 2020,
    poster: "assets/images/poster_1.jpg",
    backdrop: "assets/images/backdrop_1.jpg",
    numOfRatings: 150212,
    rating: 7.3,
    criticsReview: 50,
    metascoreRating: 44,
    genra: ["Action", "Drama"],
    plot:
        "Based on the Valiant Comics character of the same name; Bloodshot stars Vin Diesel as Marine Ray Garrison. When he and his wife are murdered, Ray is resurrected by a secret team of scientists. Enhanced with nanotechnology, he becomes a superhuman, biotech killing machine. As Ray first trains with fellow super-soldiers, he cannot recall anything from his former life. But when his memories flood back and he remembers the man that killed both him and his wife, he breaks out of the facility hellbent on revenge, only to discover that there's more to the conspiracy than he originally thought.",
    watchType: "PG-13",
    watchTime: "1h 49min",
    cast: [
      {
        "orginalName": "Vin Diesel",
        "movieName": "	Bloodshot",
        "image": "assets/images/1_11.jpg",
      },
      {
        "orginalName": "Eiza González",
        "movieName": "KT",
        "image": "assets/images/1_22.jpg",
      },
      {
        "orginalName": "Sam Heughan",
        "movieName": "Jimmy Dalton",
        "image": "assets/images/1_3.jpg",
      },
      {
        "orginalName": "Toby Kebbell",
        "movieName": "Martin Axe",
        "image": "assets/images/1_4.jpg",
      },
    ],
  ),
  Movie(
    id: 2,
    title: "Ford v Ferrari",
    year: 2019,
    poster: "assets/images/poster_2.jpg",
    backdrop: "assets/images/backdrop_2.jpg",
    numOfRatings: 313331,
    rating: 8.1,
    criticsReview: 364,
    metascoreRating: 81,
    genra: ["Action", "Biography", "Drama"],
    plot:
        "As Enzo Ferrari's fast Rosso-Corsa racing cars dominate the mid-1960s motorsport world, the American car designer, Carroll Shelby, is forced to retire after winning the demanding 1959 '24 Hours of Le Mans' endurance race. But, before long, an unexpected proposition by the Vice President of Henry Ford's motor company, Lee Iacocca, will offer an opportunity to beat the Italians at their own game. Now, under those pressing circumstances, the British sports car driver and racing engineer, Ken Miles, reluctantly agrees to lend a hand and improve the firm's image, as Ford's race team has less than ninety days to rewrite history. As a result, the non-conformist duo comes up with the mighty Ford GT40 Mk I high-performance racing car. Can Shelby and Miles break Ferrari's streak?",
    watchType: "PG-13",
    watchTime: "2h 32min",
    cast: [
      {
        "orginalName": "James Mangold",
        "movieName": "Director",
        "image": "assets/images/actor_1.png",
      },
      {
        "orginalName": "Matt Damon",
        "movieName": "Carroll",
        "image": "assets/images/actor_2.png",
      },
      {
        "orginalName": "Christian Bale",
        "movieName": "Ken Miles",
        "image": "assets/images/actor_3.png",
      },
      {
        "orginalName": "Caitriona Balfe",
        "movieName": "Mollie",
        "image": "assets/images/actor_4.png",
      },
    ],
  ),
  Movie(
    id: 3,
    title: "Onward",
    year: 2020,
    poster: "assets/images/poster_3.jpg",
    backdrop: "assets/images/backdrop_3.jpg",
    numOfRatings: 113606,
    rating: 7.4,
    criticsReview: 325,
    metascoreRating: 61,
    genra: ["Animation", "Adventure", "Comedy"],
    plot:
        "In a suburban fantasy world, two teenage elf brothers, Ian and Barley Lightfoot, go on a journey to discover if there is still a little magic left out there in order to spend one last day with their father, who died when they were too young to remember him. Like any good quest, their journey is filled with magic spells, cryptic maps, impossible obstacles and unimaginable discoveries. When the boys' fearless mom, Laurel, realizes that her sons are missing, she teams up with the legendary winged-lion-scorpion former warrior -- The Manticore -- and heads off to find them. Perilous curses aside, this one magical day could mean more than any of them ever dreamed.",
    watchType: "PG",
    watchTime: "1h 42min",
    cast: [
      {
        "orginalName": "Tom Holland",
        "movieName": "Ian Lightfoot (voice)",
        "image": "assets/images/3_1.jpg",
      },
      {
        "orginalName": "Chris Pratt",
        "movieName": "Barley Lightfoot (voice)",
        "image": "assets/images/3_2.jpg",
      },
      {
        "orginalName": "Julia Louis-Dreyfus",
        "movieName": "Laurel Lightfoot (voice)",
        "image": "assets/images/3_3.jpg",
      },
      {
        "orginalName": "Octavia Spencer",
        "movieName": "The Manticore (voice)",
        "image": "assets/images/3_4.jpg",
      },
    ],
  ),
  Movie(
    id: 4,
    title: "The Nevers",
    year: 2021,
    poster: "assets/images/the_nevers_official_poster.jpg",
    backdrop: "assets/images/the_nevers_backdrop.jpg",
    numOfRatings: 9080,
    rating: 7.4,
    criticsReview: 21,
    metascoreRating: 79,
    genra: ["Action", "Drama", "Fantasy", "Sci-Fi", "Thriller"],
    plot:
        "An epic tale following a gang of Victorian women who find themselves with unusual abilities, relentless enemies, and a mission that might change the world.",
    watchType: "TV-MA",
    watchTime: "58min",
    cast: [
      {
        "orginalName": "Laura Donnelly",
        "movieName": "Amalia True",
        "image": "assets/images/4_1.jpg",
      },
      {
        "orginalName": "Ann Skelly",
        "movieName": "Penance Adair",
        "image": "assets/images/4_2.jpg",
      },
      {
        "orginalName": "Olivia Williams",
        "movieName": "Lavinia Bidlow",
        "image": "assets/images/4_3.jpg",
      },
      {
        "orginalName": "James Norton",
        "movieName": "Hugo Swan",
        "image": "assets/images/4_4.jpg",
      },
    ],
  ),
  Movie(
    id: 5,
    title: "The Innocent",
    year: 2021,
    poster: "assets/images/the_innocent_poster.jpg",
    backdrop: "assets/images/the_innocent_backdrop.jpg",
    numOfRatings: 10624,
    rating: 8.0,
    criticsReview: 168,
    metascoreRating: 79,
    genra: ["Crime", "Drama", "Mystrey", "Thriller"],
    plot:
        "Mateo Vidal is jailed for negligent homicide for 4 years and when is released he makes a living with his beloved Olivia. Once their life has stabilized a phone call will change everything in the couple, the past leaves no one behind and many secrets will force them to try to prove their innocence.",
    watchType: "TV-MA",
    watchTime: "7h 47min",
    cast: [
      {
        "orginalName": "Mario Casas",
        "movieName": "Mateo Vidal",
        "image": "assets/images/5_1.jpg",
      },
      {
        "orginalName": "Xavi Sáez",
        "movieName": "Sáez",
        "image": "assets/images/5_2.jpg",
      },
      {
        "orginalName": "Santi Pons",
        "movieName": " Gallardo",
        "image": "assets/images/5_3.jpg",
      },
      {
        "orginalName": "Sam Feuer",
        "movieName": "Anibal",
        "image": "assets/images/5_4.jpg",
      },
    ],
  ),
  Movie(
    id: 6,
    title: "Jupiter's Legacy",
    year: 2021,
    poster: "assets/images/jupiters_legacy_poster2.jpg",
    backdrop: "assets/images/jupiters_legacy_backdrop.jpg",
    numOfRatings: 19851,
    rating: 6.9,
    criticsReview: 57,
    metascoreRating: 79,
    genra: ["Action", "Adventure", "Drama", "Thriller"],
    plot:
        "The first generation of superheroes kept the world safe for 90 years. Now the years are different, the world is changing and the enemies are getting stronger. It is time for the new generation of superheroes to accept the legacy of their fathers and to continue their work based on morality and justice.",
    watchType: "TV-MA",
    watchTime: "56min",
    cast: [
      {
        "orginalName": "Josh Duhamel",
        "movieName": "Sheldon Sampson",
        "image": "assets/images/6_1.jpg",
      },
      {
        "orginalName": "Ben Daniels",
        "movieName": "Brainwave",
        "image": "assets/images/6_2.jpg",
      },
      {
        "orginalName": "Leslie Bibb",
        "movieName": "Grace Kennedy-Sampson",
        "image": "assets/images/6_3.png",
      },
      {
        "orginalName": "Andrew Horton",
        "movieName": "Brandon Sampson",
        "image": "assets/images/6_4.jpg",
      },
    ],
  ),
  Movie(
    id: 7,
    title: "Mare of Easttown",
    year: 2021,
    poster: "assets/images/mare_of_easttown_poster.jpg",
    backdrop: "assets/images/mare_of_easttown_backdrop.jpeg",
    numOfRatings: 19851,
    rating: 8.5,
    criticsReview: 23,
    metascoreRating: 79,
    genra: ["Action", "Mystery", "Drama", "Thriller"],
    plot:
        "A detective in a small Pennsylvania town investigates a local murder while trying to keep her life from falling apart.",
    watchType: "TV-MA",
    watchTime: "6h 43min",
    cast: [
      {
        "orginalName": "Kate Winslet",
        "movieName": "Detective Mare Sheehan",
        "image": "assets/images/7_1.jpeg",
      },
      {
        "orginalName": "Jean Smart",
        "movieName": "Helen Fahey",
        "image": "assets/images/7_2.jpg",
      },
      {
        "orginalName": "Julianne Nicholson",
        "movieName": "Lori Ross",
        "image": "assets/images/7_3.jpg",
      },
      {
        "orginalName": "Angourie Rice",
        "movieName": "Siobhan Sheehan",
        "image": "assets/images/7_4.jpg",
      },
    ],
  ),
  Movie(
    id: 8,
    title: "The Handmaid's Tale",
    year: 2017,
    poster: "assets/images/the_handmaids_tale_poster.jpg",
    backdrop: "assets/images/the_handmaids_tale_backdrop.jpg",
    numOfRatings: 182379,
    rating: 8.4,
    criticsReview: 103,
    metascoreRating: 79,
    genra: ["Sci-Fi", "Mystery", "Thriller"],
    plot:
        "A religion-based autocracy has taken over most of the United States, renaming the country Gilead. In this country women are second-class citizens. Anyone trying to escape is punished. One such person is June, who is captured while trying to escape with her husband and child and is sentenced to be a handmaid, bearing children for childless government officials. As a handmaid, June is renamed Offred. This is her story.",
    watchType: "TV-MA",
    watchTime: "1h",
    cast: [
      {
        "orginalName": "Elisabeth Moss",
        "movieName": "June Osborne",
        "image": "assets/images/8_1.jpg",
      },
      {
        "orginalName": "Yvonne Strahovski",
        "movieName": "Serena Joy Waterford",
        "image": "assets/images/8_2.jpg",
      },
      {
        "orginalName": "Joseph Fiennes",
        "movieName": "Fred Waterford",
        "image": "assets/images/8_3.jpg",
      },
      {
        "orginalName": "Ann Dowd",
        "movieName": "Aunt Lydia Clements",
        "image": "assets/images/8_4.jpeg",
      },
    ],
  ),
  Movie(
    id: 9,
    title: "Shadow and Bone",
    year: 2021,
    poster: "assets/images/shadow_and_bone_poster.jpg",
    backdrop: "assets/images/shadow_and_bone_backdrop.jpg",
    numOfRatings: 43463,
    rating: 7.8,
    criticsReview: 60,
    metascoreRating: 79,
    genra: ["Action", "Adventure", "Drama"],
    plot:
        "In a world where dark forces have taken over, a young mapmaker, Alina Starkov, accidentally discovers that she has the power to change the fate of the war. She is the only one who has the power to summon light and this will make her play a key role in this war.",
    watchType: "TV-14",
    watchTime: "55min",
    cast: [
      {
        "orginalName": "Jessie Mei Li",
        "movieName": "Alina Starkov",
        "image": "assets/images/9_1.jpg",
      },
      {
        "orginalName": "Archie Renaux",
        "movieName": "Malyen Oretsev",
        "image": "assets/images/9_2.jpg",
      },
      {
        "orginalName": "Freddy Carter",
        "movieName": "Kaz Brekker",
        "image": "assets/images/9_3.jpg",
      },
      {
        "orginalName": "Amita Suman",
        "movieName": "Inej Ghafa",
        "image": "assets/images/9_4.jpg",
      },
    ],
  ),
  Movie(
    id: 10,
    title: "Love, Death & Robots",
    year: 2019,
    poster: "assets/images/love_death&robots_poster.jpg",
    backdrop: "assets/images/love_death&robots_backdrop.jpg",
    numOfRatings: 109109,
    rating: 8.5,
    criticsReview: 54,
    metascoreRating: 79,
    genra: ["Animation", "Short", "Comedy"],
    plot:
        "Love, Death + Robots is a 5-time Emmy winning animation anthology series produced by Blur Studio. Launched in March of 2019 on Netflix, Love, Death + Robots delivers a variety of style and story unlike anything else, spanning the genres of science fiction, fantasy, comedy, horror, and more. Created by Tim Miller with David Fincher as executive producer, the series brings together a global team of directors and animation studios to push and expand the medium. Eighteen shorts in all, Love, Death + Robots has something for everyone.",
    watchType: "TV-MA",
    watchTime: "15min",
    cast: [
      {
        "orginalName": "Scott Whyte",
        "movieName": "Future Nazi",
        "image": "assets/images/10_1.jpg",
      },
      {
        "orginalName": "Nolan North",
        "movieName": "Detective Briggs",
        "image": "assets/images/10_2.jpg",
      },
      {
        "orginalName": "Steven Pacey",
        "movieName": "Rail Man",
        "image": "assets/images/10_3.jpg",
      },
      {
        "orginalName": "Emily O'Brien",
        "movieName": "Eve",
        "image": "assets/images/10_4.jpg",
      },
    ],
  ),
  Movie(
    id: 11,
    title: "Game of Thrones",
    year: 2011,
    poster: "assets/images/game_of_thrones_poster.jpg",
    backdrop: "assets/images/game_of_thrones_backdrop.jpg",
    numOfRatings: 1810807,
    rating: 9.3,
    criticsReview: 341,
    metascoreRating: 79,
    genra: ["Action", "Adventure", "Drama"],
    plot:
        "In the mythical continent of Westeros, several powerful families fight for control of the Seven Kingdoms. As conflict erupts in the kingdoms of men, an ancient enemy rises once again to threaten them all. Meanwhile, the last heirs of a recently usurped dynasty plot to take back their homeland from across the Narrow Sea.",
    watchType: "TV-MA",
    watchTime: "57min",
    cast: [
      {
        "orginalName": "Peter Dinklage",
        "movieName": "Tyrion Lannister",
        "image": "assets/images/11_1.jpg",
      },
      {
        "orginalName": "Lena Headey",
        "movieName": "Cersei Lannister",
        "image": "assets/images/11_2.jpeg",
      },
      {
        "orginalName": "Emilia Clarke",
        "movieName": "Daenerys Targaryen",
        "image": "assets/images/11_3.jpg",
      },
      {
        "orginalName": "Kit Harington",
        "movieName": "Jon Snow",
        "image": "assets/images/11_4.jpg",
      },
    ],
  ),
  Movie(
    id: 12,
    title: "StartUp",
    year: 2016,
    poster: "assets/images/startUp_poster.jpg",
    backdrop: "assets/images/startUp_backdrop.jpg",
    numOfRatings: 14381,
    rating: 8.0,
    criticsReview: 6,
    metascoreRating: 79,
    genra: ["Crime", "Thriller"],
    plot:
        "Miami - A desperate banker needs to conceal stolen money. A Haitian-American gang lord wants to go legit. A Cuban-American hacker has an idea that will revolutionize the very future of money itself. Forced to work together, they unwittingly create their version of the American dream - organized crime 2.0.",
    watchType: "Not Rated",
    watchTime: "44min",
    cast: [
      {
        "orginalName": "Adam Brody",
        "movieName": "Nick Talman",
        "image": "assets/images/12_1.jpg",
      },
      {
        "orginalName": "Edi Gathegi",
        "movieName": "Ronald Dacey",
        "image": "assets/images/12_2.jpg",
      },
      {
        "orginalName": "Otmara Marrero",
        "movieName": "Izzy Morales",
        "image": "assets/images/12_3.jpg",
      },
      {
        "orginalName": "Kristen Ariza",
        "movieName": "Tamara Dacey",
        "image": "assets/images/12_4.jpeg",
      },
    ],
  ),
  Movie(
    id: 13,
    title: "Grey's Anatomy",
    year: 2005,
    poster: "assets/images/greys_anatomy_poster.jpg",
    backdrop: "assets/images/greys_anatomy_backdrop.jpg",
    numOfRatings: 259068,
    rating: 7.5,
    criticsReview: 49,
    metascoreRating: 79,
    genra: ["Drama", "Romance"],
    plot:
        "A medical based drama centered around Meredith Grey, an aspiring surgeon and daughter of one of the best surgeons, Dr. Ellis Grey. Throughout the series, Meredith goes through professional and personal challenges along with fellow surgeons at Seattle Grace Hospital.",
    watchType: "TV-14",
    watchTime: "41min",
    cast: [
      {
        "orginalName": "Ellen Pompeo",
        "movieName": "Dr. Meredith Grey",
        "image": "assets/images/13_1.jpg",
      },
      {
        "orginalName": "Chandra Wilson",
        "movieName": "Dr. Miranda Bailey",
        "image": "assets/images/13_2.jpg",
      },
      {
        "orginalName": "James Pickens Jr.",
        "movieName": "Dr. Richard Webber",
        "image": "assets/images/13_3.jpg",
      },
      {
        "orginalName": "Justin Chambers",
        "movieName": "Dr. Alex Karev",
        "image": "assets/images/13_4.jpeg",
      },
    ],
  ),
  Movie(
    id: 14,
    title: "Those Who Wish Me Dead",
    year: 2021,
    poster: "assets/images/those_who_wish_me_dead_poster.jpg",
    backdrop: "assets/images/those_who_wish_me_dead_backdrop.jpg",
    numOfRatings: 14638,
    rating: 6.0,
    criticsReview: 108,
    metascoreRating: 58,
    genra: ["Drama", "Action", "Thriller"],
    plot:
        "A teenage murder witness finds himself pursued by twin assassins in the Montana wilderness with a survival expert tasked with protecting him -- and a forest fire threatening to consume them all.",
    watchType: "R",
    watchTime: "1h 40min",
    cast: [
      {
        "orginalName": "Angelina Jolie",
        "movieName": "Hannah",
        "image": "assets/images/14_1.jpg",
      },
      {
        "orginalName": "Finn Little",
        "movieName": "Connor",
        "image": "assets/images/14_2.jpeg",
      },
      {
        "orginalName": "Jon Bernthal",
        "movieName": "Ethan",
        "image": "assets/images/14_3.jpg",
      },
      {
        "orginalName": "Aidan Gillen",
        "movieName": "Jack",
        "image": "assets/images/14_4.jpg",
      },
    ],
  ),
  Movie(
    id: 15,
    title: "Mortal Kombat",
    year: 2021,
    poster: "assets/images/mortal_kombat_poster.jpg",
    backdrop: "assets/images/mortal_kombat_backdrop.jpg",
    numOfRatings: 97998,
    rating: 6.2,
    criticsReview: 217,
    metascoreRating: 44,
    genra: ["Adventure", "Action", "Fantasy"],
    plot:
        "MMA fighter Cole Young (Lewis Tan), accustomed to taking a beating for money, is unaware of his heritage-or why Outworld's Emperor Shang Tsung (Chin Han) has sent his best warrior, Sub-Zero (Joe Taslim), an otherworldly Cryomancer, to hunt Cole down. Fearing for his family's safety, Cole goes in search of Sonya Blade (Jessica McNamee) at the direction of Jax (Mehcad Brooks), a Special Forces Major who bears the same strange dragon marking Cole was born with. Soon, he finds himself at the temple of Lord Raiden (Tadanobu Asano), an Elder God and the protector of Earthrealm, who grants sanctuary to those who bear the mark. Here, Cole trains with experienced warriors Liu Kang (Ludi Lin), Kung Lao (Max Huang) and rogue mercenary Kano (Josh Lawson), as he prepares to stand with Earth's greatest champions against the enemies of Outworld in a high stakes battle for the universe. But will Cole be pushed hard enough to unlock his arcana-the immense power from within his soul-in time to save not...",
    watchType: "R",
    watchTime: "1h 50min",
    cast: [
      {
        "orginalName": "Lewis Tan",
        "movieName": "Cole Young",
        "image": "assets/images/15_1.jpg",
      },
      {
        "orginalName": "Jessica McNamee",
        "movieName": "Sonya Blade",
        "image": "assets/images/15_2.jpg",
      },
      {
        "orginalName": "Josh Lawson",
        "movieName": "Kano",
        "image": "assets/images/15_3.jpg",
      },
      {
        "orginalName": "Joe Taslim",
        "movieName": "Bi-Han / Sub-Zero",
        "image": "assets/images/15_4.jpg",
      },
    ],
  ),
  Movie(
    id: 16,
    title: "The Woman in the Window",
    year: 2021,
    poster: "assets/images/the_woma_in_the_window_poster.jpg",
    backdrop: "assets/images/the_woma_in_the_window_backdrop.jpg",
    numOfRatings: 28162,
    rating: 5.7,
    criticsReview: 133,
    metascoreRating: 40,
    genra: ["Crime", "Drama", "Mystery"],
    plot:
        "Living in denial, the depressed, pill-popping child psychologist, Anna Fox, has holed herself up in her eerily vacant, ill-lit Manhattan brownstone apartment for the past ten long months, separated from her husband and their eight-year-old daughter. While unsuccessfully grappling with agoraphobia and intense panic attacks, suddenly, the Russells move in across the street, and brimming with curiosity, Anna decides to distract attention away from her problems by peeking into the lives of the unsuspecting new tenants. Then, one night, tensions flare, a deadly kitchen knife gleams in the dim light, and before long, someone ends up dead. Has troubled Anna, indeed, witnessed a gruesome scene of blood-stained domestic violence or is her wine-addled mind playing cruel tricks on her?",
    watchType: "R",
    watchTime: "1h 40min",
    cast: [
      {
        "orginalName": "Amy Adams",
        "movieName": "Anna Fox",
        "image": "assets/images/16_1.jpg",
      },
      {
        "orginalName": "Fred Hechinger",
        "movieName": "Ethan Russell",
        "image": "assets/images/16_2.jpg",
      },
      {
        "orginalName": "Gary Oldman",
        "movieName": "Alistair Russell",
        "image": "assets/images/16_3.jpg",
      },
      {
        "orginalName": "Julianne Moore",
        "movieName": "Jane Russell 1 (Katie)",
        "image": "assets/images/16_4.jpg",
      },
    ],
  ),
  Movie(
    id: 17,
    title: "Spiral",
    year: 2021,
    poster: "assets/images/spiral_poster.jpg",
    backdrop: "assets/images/spiral_backdrop.jpg",
    numOfRatings: 4213,
    rating: 6.0,
    criticsReview: 117,
    metascoreRating: 39,
    genra: ["Crime", "Horror", "Mystery"],
    plot:
        "Working in the shadow of his father, an esteemed police veteran (Samuel L. Jackson), brash Detective Ezekiel 'Zeke' Banks (Chris Rock) and his rookie partner (Max Minghella) take charge of a grisly investigation into murders that are eerily reminiscent of the city's gruesome past. Unwittingly entrapped in a deepening mystery, Zeke finds himself at the center of the killer's morbid game.",
    watchType: "R",
    watchTime: "1h 33min",
    cast: [
      {
        "orginalName": "Chris Rock",
        "movieName": "Detective Zeke Banks",
        "image": "assets/images/17_1.jpg",
      },
      {
        "orginalName": "Max Minghella",
        "movieName": "Detective William Schenk",
        "image": "assets/images/17_2.jpg",
      },
      {
        "orginalName": "Samuel L. Jackson",
        "movieName": "Marcus Banks",
        "image": "assets/images/17_3.jpg",
      },
      {
        "orginalName": "Marisol Nichols",
        "movieName": "Captain Angie Garza",
        "image": "assets/images/17_4.jpg",
      },
    ],
  ),
  Movie(
    id: 18,
    title: "Wrath of Man",
    year: 2021,
    poster: "assets/images/wrath_of_man_poster2.jpeg",
    backdrop: "assets/images/wrath_of_man_backdrop.jpeg",
    numOfRatings: 7151,
    rating: 7.4,
    criticsReview: 99,
    metascoreRating: 57,
    genra: ["Action", "Thriller"],
    plot:
        "The plot follows H, a cold and mysterious character working at a cash truck company responsible for moving hundreds of millions of dollars around Los Angeles each week.",
    watchType: "R",
    watchTime: "1h 59min",
    cast: [
      {
        "orginalName": "Jason Statham",
        "movieName": "H",
        "image": "assets/images/18_1.jpg",
      },
      {
        "orginalName": "Holt McCallany",
        "movieName": "Bullet",
        "image": "assets/images/18_2.jpg",
      },
      {
        "orginalName": "Rocci Williams",
        "movieName": "Hollow Bob",
        "image": "assets/images/18_3.jpeg",
      },
      {
        "orginalName": "Josh Hartnett",
        "movieName": "Boy Sweat Dave",
        "image": "assets/images/18_4.jpg",
      },
    ],
  ),
  Movie(
    id: 19,
    title: "Tom Clancy's Without Remorse",
    year: 2021,
    poster: "assets/images/tom_clancys_without_remorse_poster.jpg",
    backdrop: "assets/images/tom_clancys_without_remorse_backdrop.jpg",
    numOfRatings: 33154,
    rating: 5.8,
    criticsReview: 142,
    metascoreRating: 41,
    genra: ["Action", "Thriller", "War"],
    plot:
        "An elite Navy SEAL uncovers an international conspiracy while seeking justice for the murder of his pregnant wife in Tom Clancy's Without Remorse, the explosive origin story of action hero John Clark - one of the most popular characters in author Tom Clancy's Jack Ryan universe. When a squad of Russian soldiers kills his family in retaliation for his role in a top-secret op, Sr. Chief John Kelly (Michael B. Jordan) pursues the assassins at all costs. Joining forces with a fellow SEAL (Jodie Turner-Smith) and a shadowy CIA agent (Jamie Bell), Kelly's mission unwittingly exposes a covert plot that threatens to engulf the U.S. and Russia in an all-out war. Torn between personal honor and loyalty to his country, Kelly must fight his enemies without remorse if he hopes to avert disaster and reveal the powerful figures behind the conspiracy.",
    watchType: "R",
    watchTime: "1h 49min",
    cast: [
      {
        "orginalName": "Michael B. Jordan",
        "movieName": "John Kelly",
        "image": "assets/images/19_1.jpg",
      },
      {
        "orginalName": "Jodie Turner-Smith",
        "movieName": "Karen Greer",
        "image": "assets/images/19_2.jpg",
      },
      {
        "orginalName": "Jamie Bell",
        "movieName": "Robert Ritter",
        "image": "assets/images/19_3.jpg",
      },
      {
        "orginalName": "Guy Pearce",
        "movieName": "Secretary Clay",
        "image": "assets/images/19_4.jpg",
      },
    ],
  ),
  Movie(
    id: 20,
    title: "Tenet",
    year: 2020,
    poster: "assets/images/tenet_poster.jpg",
    backdrop: "assets/images/tenet_backdrop.jpg",
    numOfRatings: 353296,
    rating: 7.4,
    criticsReview: 480,
    metascoreRating: 69,
    genra: ["Action", "Thriller", "Sci-Fi"],
    plot:
        "In a twilight world of international espionage, an unnamed CIA operative, known as The Protagonist, is recruited by a mysterious organization called Tenet to participate in a global assignment that unfolds beyond real time. The mission: prevent Andrei Sator, a renegade Russian oligarch with precognition abilities, from starting World War III. The Protagonist will soon master the art of 'time inversion' as a way of countering the threat that is to come.",
    watchType: "PG-13",
    watchTime: "2h 30min",
    cast: [
      {
        "orginalName": "Robert Pattinson",
        "movieName": "Neil",
        "image": "assets/images/20_1.jpg",
      },
      {
        "orginalName": "John David Washington",
        "movieName": "Protagonist",
        "image": "assets/images/20_2.jpeg",
      },
      {
        "orginalName": "Clémence Poésy",
        "movieName": "Barbara",
        "image": "assets/images/20_3.jpg",
      },
      {
        "orginalName": "Dimple Kapadia",
        "movieName": "	Priya",
        "image": "assets/images/20_4.jpg",
      },
    ],
  ),
  Movie(
    id: 21,
    title: "Things Heard & Seen",
    year: 2021,
    poster: "assets/images/things_heard&seen_poster.jpg",
    backdrop: "assets/images/things_heard&seen_backdrop.jpg",
    numOfRatings: 17438,
    rating: 5.3,
    criticsReview: 102,
    metascoreRating: 49,
    genra: ["Drama", "Horror", "Mystery"],
    plot:
        "A Manhattan artist relocates her young family to a historic hamlet in the Hudson Valley. As she settles into a new life, she begins to suspect that her marriage has a sinister darkness, one that rivals her new home's history. Based on the acclaimed novel by Elizabeth Brundange..",
    watchType: "TV-MA",
    watchTime: "2h 1min",
    cast: [
      {
        "orginalName": "James Norton",
        "movieName": "George Claire",
        "image": "assets/images/4_4.jpg",
      },
      {
        "orginalName": "Ana Sophia Heger",
        "movieName": "Franny Claire",
        "image": "assets/images/21_2.jpg",
      },
      {
        "orginalName": "Amanda Seyfried",
        "movieName": "Catherine Claire",
        "image": "assets/images/21_3.jpg",
      },
      {
        "orginalName": "Charlotte Maier",
        "movieName": "	Peg",
        "image": "assets/images/21_4.jpg",
      },
    ],
  ),
  Movie(
    id: 22,
    title: "Army of the Dead",
    year: 2021,
    poster: "assets/images/army_of_the_dead_poster.jpg",
    backdrop: "assets/images/army_of_the_dead_backdrop.jpg",
    numOfRatings: 9948,
    rating: 6.6,
    criticsReview: 106,
    metascoreRating: 57,
    genra: ["Action", "Crime", "Horror"],
    plot:
        "Following a zombie outbreak in Las Vegas, a group of mercenaries take the ultimate gamble, venturing into the quarantine zone to pull off the greatest heist ever attempted.",
    watchType: "R",
    watchTime: "2h 28min",
    cast: [
      {
        "orginalName": "Dave Bautista",
        "movieName": "Scott Ward",
        "image": "assets/images/22_1.jpg",
      },
      {
        "orginalName": "Ella Purnell",
        "movieName": "Kate Ward",
        "image": "assets/images/22_2.jpg",
      },
      {
        "orginalName": "Omari Hardwick",
        "movieName": "Vanderohe",
        "image": "assets/images/22_3.jpg",
      },
      {
        "orginalName": "Ana de la Reguera",
        "movieName": "Maria Cruz",
        "image": "assets/images/22_4.jpg",
      },
    ],
  ),
  Movie(
    id: 23,
    title: "Oxygen",
    year: 2021,
    poster: "assets/images/oxygen_poster.jpg",
    backdrop: "assets/images/oxygen_backdrop.jpeg",
    numOfRatings: 13959,
    rating: 6.5,
    criticsReview: 108,
    metascoreRating: 66,
    genra: ["Drama", "Fanstasy", "Sci-Fi"],
    plot:
        "A woman wakes in a cryogenic chamber with no recollection of how she got there. As she's running out of oxygen, she must rebuild her memory to find a way out of her nightmare.",
    watchType: "TV-MA",
    watchTime: "1h 40min",
    cast: [
      {
        "orginalName": "Mélanie Laurent",
        "movieName": "Elizabeth 'Liz' Hansen",
        "image": "assets/images/23_1.jpg",
      },
      {
        "orginalName": "Mathieu Amalric",
        "movieName": "M.I.L.O. (voice)",
        "image": "assets/images/23_2.jpg",
      },
      {
        "orginalName": "Malik Zidi",
        "movieName": "Léo Ferguson",
        "image": "assets/images/23_3.jpg",
      },
      {
        "orginalName": "Laura Boujenah",
        "movieName": "Alice Hansen",
        "image": "assets/images/23_4.png",
      },
    ],
  ),
];
